/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#21143a",
        "on-tertiary-container": "#5e551e",
        "surface-container-low": "#1c1b1e",
        "outline": "#948f98",
        "platform-bilibili": "#6DBCEB",
        "tertiary-fixed": "#f0e49d",
        "on-secondary": "#1a2b6a",
        "background": "#141316",
        "surface-variant": "#363437",
        "on-secondary-fixed-variant": "#334282",
        "surface-raised": "var(--surface-3)",
        "on-secondary-fixed": "#001454",
        "primary": "var(--accent)",
        "border-default": "var(--border-default)",
        "border-subtle": "var(--border-subtle)",
        "surface-bright": "#3a383c",
        "border-strong": "var(--border-strong)",
        "on-error": "#690005",
        "surface-overlay": "var(--surface-overlay)",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#201c00",
        "accent-subtle": "var(--accent-subtle)",
        "surface-container-high": "#2b292c",
        "secondary-fixed-dim": "#b8c4ff",
        "surface-container-lowest": "#0f0e10",
        "tertiary-container": "#d7cb87",
        "on-primary-fixed-variant": "#4d4069",
        "surface-container": "#211f22",
        "tertiary": "#f4e7a1",
        "on-surface-variant": "#cbc4ce",
        "on-primary-container": "#5b4e78",
        "text-primary": "var(--text-primary)",
        "secondary": "#b8c4ff",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        "on-secondary-container": "#a2b1f9",
        "surface-container-highest": "#363437",
        "on-primary": "var(--on-primary)",
        "platform-netease": "#D84E4E",
        "primary-fixed-dim": "#cfbfef",
        "inverse-on-surface": "#323033",
        "bg-base": "var(--surface-0)",
        "surface-panel": "var(--surface-panel)",
        "on-tertiary": "#373100",
        "surface-dim": "#141316",
        "on-background": "#e6e1e5",
        "inverse-surface": "#e6e1e5",
        "on-surface": "#e6e1e5",
        "secondary-container": "#334282",
        "outline-variant": "#49454e",
        "primary-fixed": "#eaddff",
        "on-tertiary-fixed-variant": "#4f4710",
        "inverse-primary": "#655782",
        "surface-tint": "#cfbfef",
        "surface-elevated": "var(--surface-4)",
        "error": "var(--error)",
        "surface": "#141316",
        "text-muted": "var(--text-tertiary)",
        "on-error-container": "#ffdad6",
        "surface-stage": "var(--surface-stage)",
        "primary-container": "#d3c2f3",
        "secondary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#d3c884"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "24px",
        "top-bar": "64px",
        "controlGap": "12px",
        "panelPadding": "16px",
        "xxl": "48px",
        "sm": "8px",
        "base": "8px",
        "right-panel": "320px",
        "dock": "96px",
        "xs": "4px",
        "stagePadding": "40px",
        "md": "16px",
        "left-rail": "260px",
        "listGap": "6px",
        "stage-max": "1500px",
        "xl": "32px",
        "toolbarGap": "8px"
      },
      fontFamily: {
        "compact": ["Geist", "sans-serif"],
        "title": ["Geist", "sans-serif"],
        "caption": ["Geist", "sans-serif"],
        "body": ["Geist", "sans-serif"],
        "micro": ["JetBrains Mono", "monospace"],
        "display": ["Geist", "sans-serif"],
        "section-label": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "compact": ["13px", {"lineHeight": "1.4", "fontWeight": "400"}],
        "title": ["24px", {"lineHeight": "1.25", "fontWeight": "600"}],
        "caption": ["12px", {"lineHeight": "1.45", "fontWeight": "400"}],
        "body": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "micro": ["10px", {"lineHeight": "1.2", "letterSpacing": "0.14em", "fontWeight": "500"}],
        "display": ["36px", {"lineHeight": "1.18", "fontWeight": "900"}],
        "section-label": ["12px", {"lineHeight": "1.45", "letterSpacing": "0.08em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
