#!/bin/sh
set -eu

gofmt -w .
git diff --exit-code -- .
go mod tidy
git diff --exit-code -- go.mod go.sum
go vet ./...
go test ./...
go run honnef.co/go/tools/cmd/staticcheck@v0.7.0 ./...
go run golang.org/x/vuln/cmd/govulncheck@v1.6.0 ./...
CGO_ENABLED=1 go test -race ./...
CGO_ENABLED=0 go build -trimpath ./...
