#!/bin/sh
set -eu

unformatted="$(gofmt -l .)"
if [ -n "$unformatted" ]; then
  printf 'gofmt is required for:\n%s\n' "$unformatted" >&2
  exit 1
fi

go run ./cmd/contractgen -check -repo ..
go test ./internal/contractspec
go mod tidy
git diff --exit-code -- go.mod go.sum
go vet ./...
go test -count=1 ./...
go run honnef.co/go/tools/cmd/staticcheck@v0.7.0 ./...
go run golang.org/x/vuln/cmd/govulncheck@v1.6.0 ./...
CGO_ENABLED=1 go test -race -count=1 ./...
CGO_ENABLED=0 go build -trimpath ./...
