// WebSocket 目的地
export const WS_DEST = {
    CHAT_SEND: 'chat.message',
    PUBLIC_CHAT_SEND: 'public-chat.message',
    CHAT_HISTORY_FETCH: 'chat.history.fetch',
    PUBLIC_CHAT_HISTORY_FETCH: 'public-chat.history.fetch',
    PLAYER_NEXT: 'control.next',
    PLAYER_PAUSE: 'control.toggle-pause',
    PLAYER_SHUFFLE: 'control.toggle-shuffle',
    PLAYER_SEEK: 'control.seek',
    PLAYER_LIKE: 'control.like',
    ENQUEUE: 'enqueue',
    ENQUEUE_PLAYLIST: 'enqueue.playlist',
    ENQUEUE_ROOM_PLAYLIST: 'enqueue.room-playlist',
    ENQUEUE_ALBUM: 'enqueue.album',
    QUEUE_TOP: 'queue.top',
    QUEUE_REMOVE: 'queue.remove',
    QUEUE_BATCH_TOP: 'queue.batch-top',
    QUEUE_BATCH_REMOVE: 'queue.batch-remove',
    QUEUE_REORDER: 'queue.reorder',
    USER_BIND: 'user.bind',
    USER_RENAME: 'user.rename',
    ROOM_CREATE: 'rooms.create',
    ROOM_DELETE: 'rooms.delete',
    SYNC_PING: 'sync.ping',
    RESYNC: 'player.resync',

    USER_ME: 'user.me',
    USERS_ONLINE: 'users.online',
    PLAYER_STATE: 'player.state',
    PLAYER_QUEUE: 'player.queue',
    PLAYER_EVENTS: 'player.events',
    SYNC_PONG: 'sync.pong',
    CHAT_MESSAGE: 'chat.message',
    PUBLIC_CHAT_MESSAGE: 'public-chat.message',
    CHAT_HISTORY: 'chat.history',
    PUBLIC_CHAT_HISTORY: 'public-chat.history',
    CHAT_PRIVATE: 'chat.private',
    ROOMS_LIST: 'rooms.list',
    ROOM_CREATED: 'rooms.created'
};
