package contractspec

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

const frontendContractVersion = "2.0.0"

type fieldSpec struct {
	Type     string
	Optional bool
}

type messageSpec struct {
	Name    string
	Payload map[string]fieldSpec
}

func goFrontendFiles() []GeneratedFile {
	client := clientMessageSpecs()
	server := serverMessageSpecs()
	return []GeneratedFile{
		jsonGeneratedFile("contracts/go/http-contract.json", httpContract()),
		jsonGeneratedFile("contracts/go/ws-client.schema.json", websocketSchema("MusicParty Go WebSocket client messages", client)),
		jsonGeneratedFile("contracts/go/ws-server.schema.json", websocketSchema("MusicParty Go WebSocket server messages", server)),
		textGeneratedFile("music-party-web/src/contracts/generated/models.ts", generatedModels()),
		textGeneratedFile("music-party-web/src/contracts/generated/http.ts", generatedHTTP()),
		textGeneratedFile("music-party-web/src/contracts/generated/websocket.ts", generatedWebSocket(client, server)),
		textGeneratedFile("music-party-web/src/contracts/generated/version.ts", fmt.Sprintf("// Code generated by backend-go/cmd/contractgen. DO NOT EDIT.\nexport const CONTRACT_VERSION = %q as const\n", frontendContractVersion)),
	}
}

func jsonGeneratedFile(path string, value any) GeneratedFile {
	content, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		panic(err)
	}
	return GeneratedFile{Path: path, Content: append(content, '\n')}
}

func textGeneratedFile(path, value string) GeneratedFile {
	return GeneratedFile{Path: path, Content: []byte(strings.TrimSpace(value) + "\n")}
}

func httpContract() map[string]any {
	return map[string]any{
		"version": frontendContractVersion,
		"runtime": "go",
		"authentication": map[string]any{
			"session":               "HttpOnly MP_SESSION cookie",
			"csrf":                  "MP_CSRF cookie and X-CSRF-Token header",
			"browserReadableTokens": false,
		},
		"models": []string{"Session", "AccountStatus", "RoomSummary", "RoomAccessResult", "RoomUpdateInput", "RoomMember", "RoomInvite", "PlatformDescriptor", "Music", "PlaylistSummary", "PlaylistTrack", "LocalTrack", "PresenceSnapshot", "APIError"},
		"error":  map[string]any{"required": []string{"status", "code", "message"}, "optional": []string{"requestId", "fieldErrors"}},
	}
}

func clientMessageSpecs() []messageSpec {
	return []messageSpec{
		{"chat.history.fetch", fields("offset", "number?", "limit", "number?")},
		{"chat.message", fields("content", "string")},
		{"control.like", fields()}, {"control.next", fields()},
		{"control.seek", fields("positionMs", "number")},
		{"control.toggle-pause", fields()}, {"control.toggle-shuffle", fields()},
		{"enqueue", fields("platform", "string", "musicId", "string", "mutationId", "string")},
		{"enqueue.album", fields("platform", "string", "albumId", "string", "mutationId", "string")},
		{"enqueue.playlist", fields("platform", "string", "playlistId", "string", "mutationId", "string")},
		{"enqueue.room-playlist", fields("playlistId", "string", "mutationId", "string")},
		{"player.resync", fields()},
		{"public-chat.history.fetch", fields("offset", "number?", "limit", "number?")},
		{"public-chat.message", fields("content", "string")},
		{"queue.batch-remove", fields("queueIds", "string[]", "mutationId", "string")},
		{"queue.batch-top", fields("queueIds", "string[]", "mutationId", "string")},
		{"queue.remove", fields("queueId", "string", "mutationId", "string")},
		{"queue.reorder", fields("mutationId", "string", "oldIndex", "number?", "newIndex", "number?", "queueId", "string?", "targetQueueId", "string?", "position", "string?")},
		{"queue.top", fields("queueId", "string", "mutationId", "string")},
		{"rooms.create", fields("name", "string", "isPrivate", "boolean?", "password", "string?")},
		{"rooms.delete", fields("roomId", "string")},
		{"sync.ping", fields("pingId", "string", "clientSendTime", "number")},
		{"user.bind", fields("platform", "string", "accountId", "string")},
		{"user.me", fields()}, {"user.rename", fields("newName", "string")}, {"users.online", fields()},
	}
}

func serverMessageSpecs() []messageSpec {
	return []messageSpec{
		directMessage("chat.history", "ChatMessage[]"),
		directMessage("chat.message", "ChatMessage"),
		{"enqueue.ack", fields("accepted", "boolean", "count", "number?", "queueId", "string?", "mutationId", "string")},
		{"enqueue.nack", fields("accepted", "boolean?", "mutationId", "string", "reason", "string", "queueVersion", "number?")},
		directMessage("player.events", "PlayerEvent"),
		{"player.state", fields("nowPlaying", "NowPlaying?", "queue", "QueueItem[]", "isShuffle", "boolean", "isPaused", "boolean", "isPauseLocked", "boolean", "isSkipLocked", "boolean", "isShuffleLocked", "boolean", "isLoading", "boolean", "serverTimestamp", "number", "stateVersion", "number", "playEpoch", "number", "queueVersion", "number")},
		directMessage("public-chat.history", "ChatMessage[]"),
		directMessage("public-chat.message", "ChatMessage"),
		{"queue.mutation.ack", fields("mutationId", "string")},
		{"queue.mutation.nack", fields("mutationId", "string", "reason", "string", "queueVersion", "number?")},
		{"queue.patch", fields("operation", "QueuePatchOperation", "queueVersion", "number", "items", "QueueItem[]?", "item", "Partial<QueueItem>?", "queue", "QueueItem[]?", "queueIds", "string[]?", "queueId", "string?", "targetQueueId", "string?", "position", "string?", "status", "string?")},
		{"queue.reorder.ack", fields("mutationId", "string")},
		{"queue.reorder.nack", fields("mutationId", "string", "reason", "string", "queueVersion", "number?")},
		directMessage("rooms.created", "RoomSummary"),
		directMessage("rooms.list", "RoomSummary[]"),
		{"sync.pong", fields("pingId", "string", "clientSendTime", "number", "serverReceiveTime", "number", "serverSendTime", "number")},
		{"user.me", fields("publicId", "string", "name", "string", "isGuest", "boolean", "role", "string", "isAdmin", "boolean")},
		directMessage("users.online", "PresenceSnapshot"),
	}
}

func directMessage(name, payloadType string) messageSpec {
	return messageSpec{Name: name, Payload: map[string]fieldSpec{"$direct": {Type: payloadType}}}
}

func directPayloadType(message messageSpec) string {
	return message.Payload["$direct"].Type
}

func fields(values ...string) map[string]fieldSpec {
	result := make(map[string]fieldSpec, len(values)/2)
	for index := 0; index < len(values); index += 2 {
		typeName := values[index+1]
		result[values[index]] = fieldSpec{Type: strings.TrimSuffix(typeName, "?"), Optional: strings.HasSuffix(typeName, "?")}
	}
	return result
}

func websocketSchema(title string, messages []messageSpec) map[string]any {
	variants := make([]any, 0, len(messages))
	for _, message := range messages {
		properties := map[string]any{
			"type":      map[string]any{"const": message.Name},
			"requestId": nullableStringSchema(),
			"roomId":    nullableStringSchema(),
		}
		requiredPayload := []string{}
		payloadProperties := map[string]any{}
		keys := sortedFieldNames(message.Payload)
		for _, name := range keys {
			field := message.Payload[name]
			payloadProperties[name] = schemaForType(field.Type)
			if !field.Optional {
				requiredPayload = append(requiredPayload, name)
			}
		}
		if payloadType := directPayloadType(message); payloadType != "" {
			properties["payload"] = schemaForType(payloadType)
		} else {
			properties["payload"] = map[string]any{"type": "object", "additionalProperties": false, "properties": payloadProperties, "required": requiredPayload}
		}
		variants = append(variants, map[string]any{"type": "object", "additionalProperties": false, "required": []string{"type", "payload"}, "properties": properties})
	}
	return map[string]any{"$schema": "https://json-schema.org/draft/2020-12/schema", "title": title, "version": frontendContractVersion, "oneOf": variants}
}

func nullableStringSchema() map[string]any { return map[string]any{"type": []string{"string", "null"}} }

func schemaForType(typeName string) map[string]any {
	if strings.HasSuffix(typeName, "[]") {
		return map[string]any{"type": "array", "items": schemaForType(strings.TrimSuffix(typeName, "[]"))}
	}
	switch typeName {
	case "string", "number", "boolean":
		jsonType := typeName
		if jsonType == "number" {
			jsonType = "number"
		}
		return map[string]any{"type": jsonType}
	case "EventMetadata":
		return map[string]any{"type": "object", "additionalProperties": map[string]any{"type": []string{"string", "number", "boolean"}}}
	default:
		return map[string]any{"type": "object", "x-typescript-type": typeName}
	}
}

func sortedFieldNames(values map[string]fieldSpec) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func generatedModels() string {
	return `// Code generated by backend-go/cmd/contractgen. DO NOT EDIT.
export type AccountType = 'guest' | 'member' | 'admin'
export type QueuePatchOperation = 'append' | 'remove' | 'move' | 'snapshot' | 'status' | 'clear'

export interface Session { publicId: string; username: string; displayName: string; role: string; guest: boolean; enabled: boolean; lastLoginAt: number | null }
export interface AccountStatus { requiresSetup: boolean }
export interface RoomSummary { roomId: string; name: string; creatorPublicId: string; createdAt: number; privateRoom: boolean; system: boolean; onlineCount: number; accessGranted: boolean }
export interface RoomAccessResult { roomId: string; accessGranted: true; expiresAt: number }
export interface RoomUpdateInput { name: string; isPrivate: boolean; password?: string; keepExistingPassword: boolean }
export interface UserSummary { publicId: string; name: string; isGuest: boolean }
export interface PresenceSnapshot { roomId: string; revision: number; users: UserSummary[] }
export interface RoomMember { roomId: string; publicId: string; role: string; createdAt: number; updatedAt: number }
export interface RoomInvite { id: string; secret?: string; label: string; expiresAt: number; permanent: boolean; usedAt?: number; revokedAt?: number }
export interface PlatformDescriptor { id: string; label: string; supportsAlbumSearch: boolean; subsonic: boolean }
export interface Music { id: string; name: string; artists: string[]; duration: number; platform: string; coverUrl: string }
export interface PlayableMusic extends Music { url: string; needsProxy: boolean }
export interface NowPlaying { music: PlayableMusic; currentPosition: number; enqueuedById?: string; enqueuedByName?: string; likedUserIds: string[]; likeMarkers: number[]; playEpoch: number; positionUpdatedAt: number }
export interface QueueItem { queueId: string; music: Music; enqueuedBy: UserSummary; status: string }
export interface PlaylistSummary { id: string; ownerPublicId?: string; roomId?: string; name: string; systemKey: string | null; trackCount: number; createdAt: number; updatedAt: number }
export interface PlaylistTrack { id: string; playlistId: string; music: Music; sortOrder: number; createdAt: number }
export interface LocalTrack extends Music { path?: string; size?: number; modifiedAt?: number }
export interface ChatMessage { id: string; userId: string; userName: string; content: string; timestamp: number; type: string }
export type PlayerEventCode = 'CONTROL_DENIED' | 'RENAME_FAILED' | 'ROOM_PASSWORD_CHANGED' | 'ROOM_DELETED' | 'ROOM_PLAYLISTS_UPDATED' | 'RESET' | 'REMOVE' | 'ERROR_LOAD' | 'SYSTEM_MESSAGE' | 'SEEK_DENIED' | 'LIKE' | 'USER_JOIN' | 'USER_LEAVE' | 'PLAY_START'
export interface PlayerEvent { code: PlayerEventCode; severity: 'info' | 'success' | 'warning' | 'error'; message: string; actor?: UserSummary; metadata?: Record<string, string | number | boolean> }
export interface APIError { status: number; code: string; message: string; requestId?: string; fieldErrors?: Record<string, string> }
`
}

func generatedHTTP() string {
	return `// Code generated by backend-go/cmd/contractgen. DO NOT EDIT.
export type { AccountStatus, APIError, LocalTrack, Music, PlatformDescriptor, PlaylistSummary, PlaylistTrack, PresenceSnapshot, RoomAccessResult, RoomInvite, RoomMember, RoomSummary, RoomUpdateInput, Session } from './models'
`
}

func generatedWebSocket(client, server []messageSpec) string {
	var output strings.Builder
	output.WriteString("// Code generated by backend-go/cmd/contractgen. DO NOT EDIT.\n")
	output.WriteString("import type { ChatMessage, NowPlaying, PlayerEvent, PresenceSnapshot, QueueItem, QueuePatchOperation, RoomSummary, UserSummary } from './models'\n\n")
	writeEnvelopeTypes(&output, client, "Client")
	writeEnvelopeTypes(&output, server, "Server")
	return output.String()
}

func writeEnvelopeTypes(output *strings.Builder, messages []messageSpec, prefix string) {
	names := make([]string, 0, len(messages))
	for _, message := range messages {
		name := exportedName(message.Name) + prefix + "Envelope"
		names = append(names, name)
		fmt.Fprintf(output, "export interface %s { type: %q; requestId?: string | null; roomId?: string | null; payload: ", name, message.Name)
		if payloadType := directPayloadType(message); payloadType != "" {
			fmt.Fprintf(output, "%s }\n", payloadType)
			continue
		}
		output.WriteString("{")
		for _, fieldName := range sortedFieldNames(message.Payload) {
			field := message.Payload[fieldName]
			optional := ""
			if field.Optional {
				optional = "?"
			}
			fmt.Fprintf(output, " %s%s: %s;", fieldName, optional, field.Type)
		}
		output.WriteString(" } }\n")
	}
	fmt.Fprintf(output, "\nexport type %sEnvelope =\n  | %s\n\n", prefix, strings.Join(names, "\n  | "))
}

func exportedName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '.' || r == '-' })
	for index := range parts {
		if parts[index] != "" {
			parts[index] = strings.ToUpper(parts[index][:1]) + parts[index][1:]
		}
	}
	return strings.Join(parts, "")
}
